[build]
  publish = "public"              # Dossier de publication contenant ton index.html
  functions = "netlify/functions" # Dossier contenant tes fonctions serverless

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200
